/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Download: typeof import('./src/components/Header/Download.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    Logo: typeof import('./src/components/Header/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Template: typeof import('./src/components/Nav/Template/index.vue')['default']
  }
}

// For TSX support
declare global {
  const Download: typeof import('./src/components/Header/Download.vue')['default']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
  const ElTooltip: typeof import('element-plus/es')['ElTooltip']
  const Layout: typeof import('./src/components/Layout/index.vue')['default']
  const Logo: typeof import('./src/components/Header/Logo.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Template: typeof import('./src/components/Nav/Template/index.vue')['default']
}