/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/Layout/components/Aside.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Header: typeof import('./src/components/Layout/components/Header.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    Main: typeof import('./src/components/Layout/components/Main.vue')['default']
    Nav: typeof import('./src/components/Layout/components/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Template: typeof import('./src/components/Nav/Template/index.vue')['default']
  }
}

// For TSX support
declare global {
  const Aside: typeof import('./src/components/Layout/components/Aside.vue')['default']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const Header: typeof import('./src/components/Layout/components/Header.vue')['default']
  const Layout: typeof import('./src/components/Layout/index.vue')['default']
  const Main: typeof import('./src/components/Layout/components/Main.vue')['default']
  const Nav: typeof import('./src/components/Layout/components/Nav.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Template: typeof import('./src/components/Nav/Template/index.vue')['default']
}